# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql

  web:
    # image: php:7.2.2-apache
    build:
      context: .
    container_name: php_web
    depends_on:
      - db
    # volumes:
    #   - ./assets/:/var/www/html/assets/
    #   - ./client/:/var/www/html/client/
    #   - ./server/:/var/www/html/server/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    external_links:
      - db:mysql
    ports:
      - "9191:80"
    environment:
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
  